services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aquisions-app-prod
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3000

    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start']
